name: Build and Deploy Frontend

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine environment tag
        id: environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "TAG=prod" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: paulchapi/roomiesmart-frontend:${{ env.TAG }}

      - name: Deploy Frontend to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd ~/roomiesmart-backend
            docker pull paulchapi/roomiesmart-frontend:${{ env.TAG }}
            docker compose -f docker-compose.dev.yml up -d frontend